server:
  port: 8085

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'

spring:
  mail:
    host: smtp.gmail.com
    port: '587'
    username: huynhhuy9693@gmail.com
    password: cyvnmufgfyvzqtvw
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: '5000'
          timeout: '5000'
          writetimeout: '5000'
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
  application:
    name: mail-service
